var x = 1;
console.log("Hello World" + x);
console.log("add by Ras 2");
console.log("Hello World babe" + x);
console.log("add by Ras");
console.log("add by Ras 2 9");
console.log("add by Hamdi");
console.log("add by nizar");
console.log("Counter Strike");
console.log("Counter Strike");
console.log("Counter canva");
console.log("Hello World " + x);
